/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Model.connect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import Model.*;
import java.io.File;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Annisa Olga Z
 */
public class TDokter extends javax.swing.JFrame {

    /**
     * Creates new form Dokter
     * @throws java.lang.Exception
     */
    public TDokter() throws Exception {
        initComponents();
        load_tabel();
    }
    public void reset_text() {
txtHarga.setText("");
txtNama.setText("");
txtJam.setText("");
txtID.setText("");
txtJadwal.setText("");

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        btnRead = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_dokter = new javax.swing.JTable();
        txtJadwal = new javax.swing.JTextField();
        txtJam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbSpesialis = new javax.swing.JComboBox();
        btndel = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_rp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("DATA DOKTER");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, 20));

        jLabel10.setText("Spesialis");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 453, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("INPUT DATA DOKTER");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 348, -1, -1));

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 386, -1, -1));

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 424, -1, -1));

        jLabel4.setText("Harga");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 491, 38, -1));

        jLabel5.setText("Jadwal");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 386, -1, -1));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 383, 166, -1));

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 418, 166, -1));
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 485, 165, -1));

        btnRead.setText("Read");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });
        getContentPane().add(btnRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 533, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 533, -1, -1));

        tbl_dokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Dokter", "Nama", "Spesialis", "Harga", "Jadwal", "Jam"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_dokter.setName(""); // NOI18N
        tbl_dokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dokterMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_dokter);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 563, 234));

        txtJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJadwalActionPerformed(evt);
            }
        });
        getContentPane().add(txtJadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 383, 166, -1));

        txtJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJamActionPerformed(evt);
            }
        });
        getContentPane().add(txtJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 418, 166, -1));

        jLabel6.setText("Jam");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 421, -1, -1));

        cbSpesialis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "'penyakit dalam'", "'Gigi'", "'Spesialis Jantung'", "'Dermatolog'", "'Spesialis Saraf'" }));
        cbSpesialis.setToolTipText("");
        cbSpesialis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSpesialisActionPerformed(evt);
            }
        });
        getContentPane().add(cbSpesialis, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 448, 165, -1));

        btndel.setText("Delete");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });
        getContentPane().add(btndel, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 533, -1, -1));

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 533, -1, -1));

        jButton1.setText("Back");
        jButton1.setAlignmentX(0.5F);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, -1, 30));

        btn_rp.setText("REPORT");
        btn_rp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rpActionPerformed(evt);
            }
        });
        getContentPane().add(btn_rp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pasien.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 680, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        reset_text();
        try {
            // TODO add your handling code here:
            load_tabel();
        } catch (Exception ex) {
            Logger.getLogger(TDokter.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnReadActionPerformed

    private void txtJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJadwalActionPerformed

    private void txtJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJamActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
       
        dokter ds = new dokter();
        ds.setId(txtID.getText());
        ds.setNamad(txtNama.getText());
        ds.setHrg(txtHarga.getText());
        ds.setJdwl(txtJadwal.getText());
        ds.setJam(txtJam.getText());
        ds.setSpsls((String) cbSpesialis.getSelectedItem());
        ds.save(ds);
        reset_text();
        try {
            load_tabel();
        } catch (Exception ex) {
            Logger.getLogger(TDokter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        // TODO add your handling code here:
        dokter ds = new dokter();
        ds.setId(txtID.getText());
        ds.delete(ds);
        reset_text();
        try {
            load_tabel();
        } catch (Exception ex) {
            Logger.getLogger(TDokter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btndelActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
    dokter ds = new dokter();
  
        ds.setId(txtID.getText());
        ds.setNamad(txtNama.getText());
        ds.setHrg(txtHarga.getText());
        ds.setJdwl(txtJadwal.getText());
        ds.setJam(txtJam.getText());
        ds.setSpsls((String) cbSpesialis.getSelectedItem());
        ds.update(ds);
        reset_text();
        try {
            load_tabel();
        } catch (Exception ex) {
            Logger.getLogger(TDokter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void cbSpesialisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSpesialisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSpesialisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        MenuAwal ss = new MenuAwal();
        ss.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbl_dokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dokterMouseClicked
        // TODO add your handling code here:
       try { int row = tbl_dokter.rowAtPoint(evt.getPoint());
String id = tbl_dokter.getValueAt(row, 0).toString();
String nama = tbl_dokter.getValueAt(row, 1).toString();
String harga = tbl_dokter.getValueAt(row, 3).toString();
String jadwal = tbl_dokter.getValueAt(row, 4).toString();
String jam = tbl_dokter.getValueAt(row, 5).toString();
String spesialis = tbl_dokter.getValueAt(row, 2).toString();
txtID.setText(String.valueOf(id));
txtNama.setText(String.valueOf(nama));
txtHarga.setText(String.valueOf(harga));
txtJadwal.setText(String.valueOf(jadwal));
txtJam.setText(String.valueOf(jam));
cbSpesialis.setSelectedItem(String.valueOf(spesialis));
} catch (Exception e) {
} 
    }//GEN-LAST:event_tbl_dokterMouseClicked

    private void btn_rpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rpActionPerformed
     connect con = new connect();
        try {
            File namafile = new File("src/gui/report1.jasper");
            JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, connect.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        } catch (Exception ex) {
            Logger.getLogger(TDokter.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    
    }//GEN-LAST:event_btn_rpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TDokter().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(TDokter.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
        private void load_tabel() throws Exception {
      DefaultTableModel model = new DefaultTableModel();
      
      model.addColumn("ID");
      model.addColumn("nama");
      model.addColumn("Spesialis");
      model.addColumn("harga");
      model.addColumn("jadwal");
      model.addColumn("jam");
      String sql="select * from dokter";
        try {
            ResultSet res = new Read().exec(sql);
            while(res.next()){
                 model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
            }
            this.tbl_dokter.setModel(model);
        } catch (SQLException ex) {
           
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btn_rp;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnedit;
    private javax.swing.JComboBox cbSpesialis;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl_dokter;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtJadwal;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
