/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.ComboBoxModel;
import Model.pasien;
import Model.Read;
import Model.connect;
import java.io.File;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author zea
 */
public class TPasien extends javax.swing.JFrame {

    /**
     * 
     * @throws java.lang.Exception
     */
    
    public TPasien() throws Exception {
        initComponents();
        load_tabel(1);
//        cari("key");
//        load_asuransi();
    }
    
public void reset_text() {
txtKTP.setText("");
txtNama.setText("");
txtAlamat.setText("");
txtTTL.setText("");
txtNoHP.setText("");
tx_cari.setText("");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNoHP = new javax.swing.JTextField();
        btnRead = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        txtKTP = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_pasien = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTTL = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnDel = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tx_cari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtNoHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 461, 166, -1));

        btnRead.setText("Read");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });
        getContentPane().add(btnRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 511, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 511, -1, -1));

        jLabel1.setText("No. KTP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 359, -1, -1));

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 394, -1, -1));

        jLabel4.setText("No.HP");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 464, 38, -1));

        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 356, -1, -1));

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 356, -1, -1));
        getContentPane().add(txtKTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 356, 166, -1));

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 391, 166, -1));

        tbl_pasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No. KTP", "Nama", "TTL", "No.HP", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_pasien.setName(""); // NOI18N
        tbl_pasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pasienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_pasien);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 510, 210));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("DATA PASIEN");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 34, -1, -1));

        jLabel10.setText("TTL");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 429, -1, -1));

        txtTTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTTLActionPerformed(evt);
            }
        });
        getContentPane().add(txtTTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 426, 166, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("INPUT DATA PASIEN");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 321, -1, -1));

        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        getContentPane().add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 511, -1, -1));

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 511, -1, -1));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, -1, -1));
        getContentPane().add(tx_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 170, -1));

        btn_cari.setText("cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, -1, -1));

        jButton2.setText("REPORT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pasien.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 700, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
       reset_text();
        try {
            load_tabel(1);
        } catch (Exception ex) {
            Logger.getLogger(TPasien.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_btnReadActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtTTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTTLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTTLActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        pasien ps = new pasien();
        String ktp = txtKTP.getText();
        String nama = txtNama.getText();
        String alamat = txtAlamat.getText();
        String hp = txtNoHP.getText();
        String ttl = txtTTL.getText();
        
       ps.setNo_ktp(ktp);
       ps.setNama(nama);
       ps.setAlamat(alamat);
       ps.setHp(hp);
       ps.setTgl_lahir(ttl);
       ps.save(ps);
       reset_text();
        try {
            load_tabel(1);
        } catch (Exception ex) {
            Logger.getLogger(TPasien.class.getName()).log(Level.SEVERE, null, ex);
        }
 

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
          pasien ps = new pasien();
          ps.setNo_ktp(txtKTP.getText());
          ps.delete(ps);
          reset_text();
        try {
            load_tabel(1);
        } catch (Exception ex) {
            Logger.getLogger(TPasien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
          pasien ps = new pasien();

       ps.setNo_ktp(txtKTP.getText());
       ps.setNama(txtNama.getText());
       ps.setAlamat(txtAlamat.getText());
       ps.setHp(txtNoHP.getText());
       ps.setTgl_lahir(txtTTL.getText());
       ps.update(ps);
       reset_text();
        try {
            load_tabel(1);
        } catch (Exception ex) {
            Logger.getLogger(TPasien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void tbl_pasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pasienMouseClicked
        // TODO add your handling code here:

try { int row = tbl_pasien.rowAtPoint(evt.getPoint());
String ktp = tbl_pasien.getValueAt(row, 0).toString();
String nama = tbl_pasien.getValueAt(row, 1).toString();
String ttl = tbl_pasien.getValueAt(row, 4).toString();
String hp = tbl_pasien.getValueAt(row, 3).toString();
String alamat = tbl_pasien.getValueAt(row, 2).toString();
txtKTP.setText(String.valueOf(ktp));
txtNama.setText(String.valueOf(nama));
txtTTL.setText(String.valueOf(ttl));
txtNoHP.setText(String.valueOf(hp));
txtAlamat.setText(String.valueOf(alamat));
} catch (Exception e) {
}
    }//GEN-LAST:event_tbl_pasienMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        MenuAwal ss = new MenuAwal();
        ss.setVisible(true);
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
         final DefaultTableModel model = new DefaultTableModel();
      
      model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
      model.addColumn("no KTP");
      model.addColumn("nama");
      model.addColumn("alamat");
      model.addColumn("kontak");
      model.addColumn("Tanggal lahir");
      String sql="select * from pasien where no_ktp like '"+tx_cari.getText() +"%' OR nama like '" +tx_cari.getText()+"%'";
        try {
            ResultSet res = new Read().exec(sql);
            while(res.next()){
                 model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});
            }
            this.tbl_pasien.setModel(model);
        } catch (SQLException ex) {
            
        } catch (Exception ex) {
            Logger.getLogger(TPasien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         connect con = new connect();
        try {
            File namafile = new File("src/gui/report2.jasper");
            JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, connect.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        } catch (Exception ex) {
            Logger.getLogger(TDokter.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TPasien().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(TPasien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
   

    
  private void load_tabel(int i) throws Exception {
      
      final DefaultTableModel model = new DefaultTableModel();
      
      model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
      model.addColumn("no KTP");
      model.addColumn("nama");
      model.addColumn("alamat");
      model.addColumn("kontak");
      model.addColumn("Tanggal lahir");
      String sql="select * from pasien";
        try {
            ResultSet res = new Read().exec(sql);
            while(res.next()){
                 model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});
            }
            this.tbl_pasien.setModel(model);
        } catch (SQLException ex) {
            
        }
       
      
      
      
      

    }
     
            

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl_pasien;
    private javax.swing.JTextField tx_cari;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtKTP;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoHP;
    private javax.swing.JTextField txtTTL;
    // End of variables declaration//GEN-END:variables
}
